
- name: Apt-get update
  ansible.builtin.command:  apt-get update  
  register: apt_get_update

- name: Show debug output

  ansible.builtin.debug: msg="{{ apt_get_update.stdout_lines }}"

- name: Apt-get upgrade
  ansible.builtin.command:  apt-get -y upgrade  
  register: apt_get_upgrade

- name: Show debug output

  ansible.builtin.debug: msg="{{ apt_get_upgrade.stdout_lines }}"

- name: Apt-get autoremove
  ansible.builtin.command:  apt-get -y autoremove  
  register: apt_get_autoremove

- name: Show debug output

  ansible.builtin.debug: msg="{{ apt_get_autoremove.stdout_lines }}"

