
- name: apt-get update
  ansible.builtin.command:  apt-get update  
  register: update

- ansible.builtin.debug:  msg="{{ update.stdout_lines }}"

- name: apt-get upgrade
  ansible.builtin.command:  apt-get -y upgrade  
  register: upgrade

- ansible.builtin.debug:  msg="{{ upgrade.stdout_lines }}"

- name: apt-get autoremove
  ansible.builtin.command:  apt-get -y autoremove  
  register: autoremove

- ansible.builtin.debug:  msg="{{ autoremove.stdout_lines }}"

