
- name: Apt-get update
  ansible.builtin.apt:
    update_cache: true
  register: apt_get_update

- name: Show debug output
  ansible.builtin.debug:
    msg: "{{ apt_get_update.stdout_lines }}"

- name: Apt-get upgrade
  ansible.builtin.apt:
    upgrade: "yes"
  register: apt_get_upgrade

- name: Show debug output
  ansible.builtin.debug:
    msg: "{{ apt_get_upgrade.stdout_lines }}"

- name: Apt-get autoremove
  ansible.builtin.apt:
    autoremove: true
  register: apt_get_autoremove

- name: Show debug output
  ansible.builtin.debug:
    msg: "{{ apt_get_autoremove.stdout_lines }}"

