
- name: Mem
  ansible.builtin.command: free -m
  register: mem_count_memcount
  changed_when: false

- name: Show debug output

  ansible.builtin.debug:
    msg: "{{ mem_count_memcount.stdout_lines }}"

