- hosts: stage_leader
  become: true
  roles:
    - bashrc
    - swapoff
    - date
    - mem_count
    - print_boot_cmdline_txt
    - cgroup
    - fstab
    - sysctl-sdcard
    - log_ramdisk
    - network-tmpfs
    - apt-hardening
    - services-headless
    - fake-hwclock
    - boot-opts
    - apt-get
    - ssd-mount
    - k3s-leader
    - docker-registry



- hosts: stage_members
  become: true
  roles:
    - bashrc
    - swapoff
    - date
    - mem_count
    - print_boot_cmdline_txt
    - cgroup
    - fstab
    - sysctl-sdcard
    - log_ramdisk
    - network-tmpfs
    - apt-hardening
    - services-headless
    - fake-hwclock
    - boot-opts
    - apt-get
    - ssd-mount
    - k3s-member
