- name: Configure stage leader
  hosts: stage_leader
  become: true
  roles:
    - bashrc
    - swapoff
    - date
    - mem_count
    - print_boot_cmdline_txt
    - cgroup
    - fstab
    - sysctl_sdcard
    - log_ramdisk
    - network_tmpfs
    - apt_hardening
    - services_headless
    - fake_hwclock
    - boot_opts
    - apt_get
    - ssd_mount
    - longhorn_prereqs
    - k3s_leader
    - docker_registry
    - longhorn
    - prometheus
    - selenium_media
    - selenium_grid

- name: Configure stage members
  hosts: stage_members
  become: true
  roles:
    - bashrc
    - swapoff
    - date
    - mem_count
    - print_boot_cmdline_txt
    - cgroup
    - fstab
    - sysctl_sdcard
    - log_ramdisk
    - network_tmpfs
    - apt_hardening
    - services_headless
    - fake_hwclock
    - boot_opts
    - apt_get
    - ssd_mount
    - longhorn_prereqs
    - k3s_member
