- name: detect boot firmware path
  stat:
    path: /boot/firmware/cmdline.txt
  register: boot_firmware

- name: set cmdline_path fact
  set_fact:
    cmdline_path: "{{ '/boot/firmware/cmdline.txt' if boot_firmware.stat.exists else '/boot/cmdline.txt' }}"

- name: add fsck.mode=skip to cmdline.txt
  lineinfile:
    path: "{{ cmdline_path }}"
    backrefs: yes
    regexp: '^((?!.*fsck\.mode=skip).+rootwait.*)$'
    line: '\1 fsck.mode=skip'
  notify: reboot
