
- name: apt-get update
  command:  apt-get update  
  register: update

- debug:  msg="{{ update.stdout_lines }}"

- name: apt-get upgrade
  command:  apt-get -y upgrade  
  register: upgrade

- debug:  msg="{{ upgrade.stdout_lines }}"

- name: apt-get autoremove
  command:  apt-get -y autoremove  
  register: autoremove

- debug:  msg="{{ autoremove.stdout_lines }}"

