# Reduce SD card write frequency by tuning dirty page writeback
vm.dirty_writeback_centisecs = 1500
vm.dirty_expire_centisecs = 6000
vm.dirty_background_ratio = 5
vm.dirty_ratio = 10
vm.swappiness = 0
