- name: Mask triggerhappy service
  ansible.builtin.systemd:
    name: triggerhappy.service
    masked: true
  ignore_errors: true

- name: Mask bluetooth service
  ansible.builtin.systemd:
    name: bluetooth.service
    masked: true
  ignore_errors: true

- name: Mask hciuart service
  ansible.builtin.systemd:
    name: hciuart.service
    masked: true
  ignore_errors: true
