- name: mask triggerhappy service
  ansible.builtin.systemd:
    name: triggerhappy.service
    masked: yes
  ignore_errors: yes

- name: mask bluetooth service
  ansible.builtin.systemd:
    name: bluetooth.service
    masked: yes
  ignore_errors: yes

- name: mask hciuart service
  ansible.builtin.systemd:
    name: hciuart.service
    masked: yes
  ignore_errors: yes
