- name: Apt-get update
  ansible.builtin.apt:
    update_cache: true
  register: apt_get_update

- name: Show debug output
  ansible.builtin.debug:
    msg: "cache updated: {{ apt_get_update.cache_updated }}"

- name: Apt-get upgrade
  ansible.builtin.apt:
    upgrade: "yes"
  register: apt_get_upgrade

- name: Show debug output
  ansible.builtin.debug:
    msg: "{{ apt_get_upgrade.stdout_lines | default(['(no output)']) }}"

- name: Apt-get autoremove
  ansible.builtin.apt:
    autoremove: true
  register: apt_get_autoremove

- name: Show debug output
  ansible.builtin.debug:
    msg: "{{ apt_get_autoremove.stdout_lines | default(['(no output)']) }}"
