- name: Mask triggerhappy service
  ansible.builtin.systemd:
    name: triggerhappy.service
    masked: true
  failed_when: false

- name: Mask bluetooth service
  ansible.builtin.systemd:
    name: bluetooth.service
    masked: true
  failed_when: false

- name: Mask hciuart service
  ansible.builtin.systemd:
    name: hciuart.service
    masked: true
  failed_when: false

- name: Set default systemd target to multi-user.target
  ansible.builtin.command: systemctl set-default multi-user.target
  register: services_headless_set_default_result
  changed_when: '"Created symlink" in services_headless_set_default_result.stdout'

- name: Mask gdm service
  ansible.builtin.systemd:
    name: gdm.service
    masked: true
  failed_when: false

- name: Mask gdm3 service
  ansible.builtin.systemd:
    name: gdm3.service
    masked: true
  failed_when: false

- name: Mask weston service
  ansible.builtin.systemd:
    name: weston.service
    masked: true
  failed_when: false

- name: Mask colord service
  ansible.builtin.systemd:
    name: colord.service
    masked: true
  failed_when: false

- name: Mask accounts-daemon service
  ansible.builtin.systemd:
    name: accounts-daemon.service
    masked: true
  failed_when: false

- name: Mask power-profiles-daemon service
  ansible.builtin.systemd:
    name: power-profiles-daemon.service
    masked: true
  failed_when: false

- name: Mask fprintd service
  ansible.builtin.systemd:
    name: fprintd.service
    masked: true
  failed_when: false

- name: Mask geoclue service
  ansible.builtin.systemd:
    name: geoclue.service
    masked: true
  failed_when: false

- name: Mask gnome-remote-desktop service
  ansible.builtin.systemd:
    name: gnome-remote-desktop.service
    masked: true
  failed_when: false

- name: Mask packagekit service
  ansible.builtin.systemd:
    name: packagekit.service
    masked: true
  failed_when: false

- name: Mask gnome-initial-setup service
  ansible.builtin.systemd:
    name: gnome-initial-setup.service
    masked: true
  failed_when: false

- name: Mask upower service
  ansible.builtin.systemd:
    name: upower.service
    masked: true
  failed_when: false

- name: Mask ModemManager service
  ansible.builtin.systemd:
    name: ModemManager.service
    masked: true
  failed_when: false

- name: Mask cups service
  ansible.builtin.systemd:
    name: cups.service
    masked: true
  failed_when: false

- name: Mask cups-browsed service
  ansible.builtin.systemd:
    name: cups-browsed.service
    masked: true
  failed_when: false

- name: Mask rtkit-daemon service
  ansible.builtin.systemd:
    name: rtkit-daemon.service
    masked: true
  failed_when: false

- name: Mask switcheroo-control service
  ansible.builtin.systemd:
    name: switcheroo-control.service
    masked: true
  failed_when: false
