
- name: swapoff
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: purge dphys-swapfile package
  ansible.builtin.apt:
    name: dphys-swapfile
    state: absent
    purge: yes

- name: remove /var/swap file
  ansible.builtin.file:
    path: /var/swap
    state: absent

