
- name: apt-get update
  shell:  apt-get update -y

- name: install Apache2-utils
  apt:
    name: apache2-utils
    state: present

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: install pip
  apt:
    name: python3-pip
    state: present

- name: install python passlib
  pip:
    name: passlib
    state: present

- name: Add htpasswd
  htpasswd: 
    state: present
    name: registry
    password: '1qazxsw2'
    path:  /home/pi/htpasswd
    mode: 0640

- name: Check if secret exists
  shell:  kubectl describe secret docker-registry-htpasswd
  register: secret_exists
  ignore_errors: yes

- name: kubectl create secret
  shell:  kubectl create secret generic docker-registry-htpasswd --from-file /home/pi/htpasswd
  register:  create_secret
  when:  secret_exists.rc == 1

- debug: msg="{{ create_secret.stdout_lines }}"
  when:  secret_exists.rc == 1

- name: kubectl describe secret
  shell:  kubectl describe secret docker-registry-htpasswd
  register: secrets
  when:  secret_exists.rc == 1

- debug: msg="{{ secrets.stdout_lines }}"
  when:  secret_exists.rc == 1

