
- name: Print /boot/cmdline.txt
  ansible.builtin.command: cat /boot/cmdline.txt
  become:  true
  register: print_boot_cmdline_txt_cmdline
  changed_when: false

- name: Show debug output
  ansible.builtin.debug:
    msg: "{{ print_boot_cmdline_txt_cmdline.stdout_lines }}"

